apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hoorbezn5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hoorbezn5-java-springboot-gitops